services:
  Buepro\Pizpalue\Service\BrandingService:
    tags:
      - name: event.listener
        identifier: 'buepro/pizpalue/set-backend-styling'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
  Buepro\Pizpalue\Service\ExtensionInstallService:
    tags:
      - name: event.listener
        identifier: 'buepro/pizpalue/finalize-extension-installation'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
